//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18051
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galaxy_Editor_2 {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Galaxy_Editor_2.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string ALL_Error {
            get {
                return ResourceManager.GetString("ALL_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No possible methods found for delegate invoke. 的本地化字符串。
        /// </summary>
        internal static string Delegates_Text1 {
            get {
                return ResourceManager.GetString("Delegates_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found multiple candidates for the main entry 的本地化字符串。
        /// </summary>
        internal static string ErrorText1 {
            get {
                return ResourceManager.GetString("ErrorText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matching  的本地化字符串。
        /// </summary>
        internal static string ErrorText10 {
            get {
                return ResourceManager.GetString("ErrorText10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matching declaration 的本地化字符串。
        /// </summary>
        internal static string ErrorText100 {
            get {
                return ResourceManager.GetString("ErrorText100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can not access a non-static property in a static context. 的本地化字符串。
        /// </summary>
        internal static string ErrorText101 {
            get {
                return ResourceManager.GetString("ErrorText101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to use struct fields outside of methods. 的本地化字符串。
        /// </summary>
        internal static string ErrorText102 {
            get {
                return ResourceManager.GetString("ErrorText102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 + is not defined for type  的本地化字符串。
        /// </summary>
        internal static string ErrorText103 {
            get {
                return ResourceManager.GetString("ErrorText103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  is only defined for (bool  的本地化字符串。
        /// </summary>
        internal static string ErrorText104 {
            get {
                return ResourceManager.GetString("ErrorText104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found no definitions of ( 的本地化字符串。
        /// </summary>
        internal static string ErrorText105 {
            get {
                return ResourceManager.GetString("ErrorText105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matching operator 的本地化字符串。
        /// </summary>
        internal static string ErrorText106 {
            get {
                return ResourceManager.GetString("ErrorText106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matched default  的本地化字符串。
        /// </summary>
        internal static string ErrorText107 {
            get {
                return ResourceManager.GetString("ErrorText107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple definitions for ( 的本地化字符串。
        /// </summary>
        internal static string ErrorText108 {
            get {
                return ResourceManager.GetString("ErrorText108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ) found. 的本地化字符串。
        /// </summary>
        internal static string ErrorText109 {
            get {
                return ResourceManager.GetString("ErrorText109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found multiple structs/classes matching  的本地化字符串。
        /// </summary>
        internal static string ErrorText11 {
            get {
                return ResourceManager.GetString("ErrorText11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - is not defined for type  的本地化字符串。
        /// </summary>
        internal static string ErrorText110 {
            get {
                return ResourceManager.GetString("ErrorText110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;! is not defined for type  的本地化字符串。
        /// </summary>
        internal static string ErrorText111 {
            get {
                return ResourceManager.GetString("ErrorText111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constant fields must be initialized. 的本地化字符串。
        /// </summary>
        internal static string ErrorText112 {
            get {
                return ResourceManager.GetString("ErrorText112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constant fields&apos; initializer must be constant. 的本地化字符串。
        /// </summary>
        internal static string ErrorText113 {
            get {
                return ResourceManager.GetString("ErrorText113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ++ and -- expressions can only reside inside methods. 的本地化字符串。
        /// </summary>
        internal static string ErrorText114 {
            get {
                return ResourceManager.GetString("ErrorText114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pointers must be cast to either int or string. 的本地化字符串。
        /// </summary>
        internal static string ErrorText115 {
            get {
                return ResourceManager.GetString("ErrorText115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected cast to 的本地化字符串。
        /// </summary>
        internal static string ErrorText116 {
            get {
                return ResourceManager.GetString("ErrorText116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected cast to string. 的本地化字符串。
        /// </summary>
        internal static string ErrorText117 {
            get {
                return ResourceManager.GetString("ErrorText117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sharp casts can only be used from pointers to int/string and vice versa. 的本地化字符串。
        /// </summary>
        internal static string ErrorText118 {
            get {
                return ResourceManager.GetString("ErrorText118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pointers must be cast from either int or string. 的本地化字符串。
        /// </summary>
        internal static string ErrorText119 {
            get {
                return ResourceManager.GetString("ErrorText119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constructors must have same name as the enclosing struct. 的本地化字符串。
        /// </summary>
        internal static string ErrorText12 {
            get {
                return ResourceManager.GetString("ErrorText12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected cast from 的本地化字符串。
        /// </summary>
        internal static string ErrorText120 {
            get {
                return ResourceManager.GetString("ErrorText120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected cast from string. 的本地化字符串。
        /// </summary>
        internal static string ErrorText121 {
            get {
                return ResourceManager.GetString("ErrorText121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to cast from  的本地化字符串。
        /// </summary>
        internal static string ErrorText122 {
            get {
                return ResourceManager.GetString("ErrorText122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   to  的本地化字符串。
        /// </summary>
        internal static string ErrorText123 {
            get {
                return ResourceManager.GetString("ErrorText123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method matching by name and number of parameters 的本地化字符串。
        /// </summary>
        internal static string ErrorText124 {
            get {
                return ResourceManager.GetString("ErrorText124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to find a matching method. 的本地化字符串。
        /// </summary>
        internal static string ErrorText125 {
            get {
                return ResourceManager.GetString("ErrorText125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matches dynamic array resize. 的本地化字符串。
        /// </summary>
        internal static string ErrorText126 {
            get {
                return ResourceManager.GetString("ErrorText126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found multiple matching methods. 的本地化字符串。
        /// </summary>
        internal static string ErrorText127 {
            get {
                return ResourceManager.GetString("ErrorText127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found multiple implicitly matching methods. 的本地化字符串。
        /// </summary>
        internal static string ErrorText128 {
            get {
                return ResourceManager.GetString("ErrorText128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Argument  的本地化字符串。
        /// </summary>
        internal static string ErrorText129 {
            get {
                return ResourceManager.GetString("ErrorText129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can only define one deconstructor in a  的本地化字符串。
        /// </summary>
        internal static string ErrorText13 {
            get {
                return ResourceManager.GetString("ErrorText13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  must be a variable, as the parameter is marked as out or ref. 的本地化字符串。
        /// </summary>
        internal static string ErrorText130 {
            get {
                return ResourceManager.GetString("ErrorText130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inline methods can only be called from inside other methods. 的本地化字符串。
        /// </summary>
        internal static string ErrorText131 {
            get {
                return ResourceManager.GetString("ErrorText131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  can not be a constant variable, as the parameter is marked as out or ref. 的本地化字符串。
        /// </summary>
        internal static string ErrorText132 {
            get {
                return ResourceManager.GetString("ErrorText132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inline methods can only be called from inside methods, constructors or properties. 的本地化字符串。
        /// </summary>
        internal static string ErrorText133 {
            get {
                return ResourceManager.GetString("ErrorText133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The condition of the if can&apos;t be a struct or array. 的本地化字符串。
        /// </summary>
        internal static string ErrorText134 {
            get {
                return ResourceManager.GetString("ErrorText134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The then and else part of a ? expression must be assignable one way or the other. 的本地化字符串。
        /// </summary>
        internal static string ErrorText135 {
            get {
                return ResourceManager.GetString("ErrorText135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The keyword this can only be used inside struct constructors, deconstructors, classes or enrichments. 的本地化字符串。
        /// </summary>
        internal static string ErrorText136 {
            get {
                return ResourceManager.GetString("ErrorText136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The keyword this can not be used in a static context. 的本地化字符串。
        /// </summary>
        internal static string ErrorText137 {
            get {
                return ResourceManager.GetString("ErrorText137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can&apos;t create a new instance of an enum. 的本地化字符串。
        /// </summary>
        internal static string ErrorText138 {
            get {
                return ResourceManager.GetString("ErrorText138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matching enum 的本地化字符串。
        /// </summary>
        internal static string ErrorText139 {
            get {
                return ResourceManager.GetString("ErrorText139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The player must be an integer literal. 的本地化字符串。
        /// </summary>
        internal static string ErrorText14 {
            get {
                return ResourceManager.GetString("ErrorText14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find a constructor matching: ( 的本地化字符串。
        /// </summary>
        internal static string ErrorText140 {
            get {
                return ResourceManager.GetString("ErrorText140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Candidate  的本地化字符串。
        /// </summary>
        internal static string ErrorText141 {
            get {
                return ResourceManager.GetString("ErrorText141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ambiguous constructor call. Found multiple matching constructor definitions. 的本地化字符串。
        /// </summary>
        internal static string ErrorText142 {
            get {
                return ResourceManager.GetString("ErrorText142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instance creation expression must be in a method, since a constructor must be called. 的本地化字符串。
        /// </summary>
        internal static string ErrorText143 {
            get {
                return ResourceManager.GetString("ErrorText143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constructors are only defined for struct types 的本地化字符串。
        /// </summary>
        internal static string ErrorText144 {
            get {
                return ResourceManager.GetString("ErrorText144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can only delete dynamically allocated types. 的本地化字符串。
        /// </summary>
        internal static string ErrorText145 {
            get {
                return ResourceManager.GetString("ErrorText145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to delete object from here, since a matching deconstructor is private. 的本地化字符串。
        /// </summary>
        internal static string ErrorText146 {
            get {
                return ResourceManager.GetString("ErrorText146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deconstructor 的本地化字符串。
        /// </summary>
        internal static string ErrorText147 {
            get {
                return ResourceManager.GetString("ErrorText147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to delete object from here, since a matching deconstructor is protected. 的本地化字符串。
        /// </summary>
        internal static string ErrorText148 {
            get {
                return ResourceManager.GetString("ErrorText148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected something of pointer type 的本地化字符串。
        /// </summary>
        internal static string ErrorText149 {
            get {
                return ResourceManager.GetString("ErrorText149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other deconstructor 的本地化字符串。
        /// </summary>
        internal static string ErrorText15 {
            get {
                return ResourceManager.GetString("ErrorText15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dynamic typed array can not put a requirement on the dimension. 的本地化字符串。
        /// </summary>
        internal static string ErrorText150 {
            get {
                return ResourceManager.GetString("ErrorText150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to assign from type  的本地化字符串。
        /// </summary>
        internal static string ErrorText151 {
            get {
                return ResourceManager.GetString("ErrorText151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   to type  的本地化字符串。
        /// </summary>
        internal static string ErrorText152 {
            get {
                return ResourceManager.GetString("ErrorText152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to assign to a const field. 的本地化字符串。
        /// </summary>
        internal static string ErrorText153 {
            get {
                return ResourceManager.GetString("ErrorText153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Used delegate 的本地化字符串。
        /// </summary>
        internal static string ErrorText154 {
            get {
                return ResourceManager.GetString("ErrorText154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inconsistent accessibility. Private types used in public context. 的本地化字符串。
        /// </summary>
        internal static string ErrorText155 {
            get {
                return ResourceManager.GetString("ErrorText155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method marked as trigger, but does not match the signature (bool, bool):bool 的本地化字符串。
        /// </summary>
        internal static string ErrorText156 {
            get {
                return ResourceManager.GetString("ErrorText156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not all code paths return a value. 的本地化字符串。
        /// </summary>
        internal static string ErrorText157 {
            get {
                return ResourceManager.GetString("ErrorText157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not all code paths of the getter return a value 的本地化字符串。
        /// </summary>
        internal static string ErrorText158 {
            get {
                return ResourceManager.GetString("ErrorText158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  to type void 的本地化字符串。
        /// </summary>
        internal static string ErrorText159 {
            get {
                return ResourceManager.GetString("ErrorText159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deconstructors must have same name as the enclosing struct. 的本地化字符串。
        /// </summary>
        internal static string ErrorText16 {
            get {
                return ResourceManager.GetString("ErrorText16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This function must return something of type  的本地化字符串。
        /// </summary>
        internal static string ErrorText160 {
            get {
                return ResourceManager.GetString("ErrorText160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The getter must return something of type  的本地化字符串。
        /// </summary>
        internal static string ErrorText161 {
            get {
                return ResourceManager.GetString("ErrorText161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter marked as out is not assigned a value 的本地化字符串。
        /// </summary>
        internal static string ErrorText162 {
            get {
                return ResourceManager.GetString("ErrorText162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No matching base constructor found. 的本地化字符串。
        /// </summary>
        internal static string ErrorText163 {
            get {
                return ResourceManager.GetString("ErrorText163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Base struct 的本地化字符串。
        /// </summary>
        internal static string ErrorText164 {
            get {
                return ResourceManager.GetString("ErrorText164", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Base constructor call matched multiple constructors. 的本地化字符串。
        /// </summary>
        internal static string ErrorText165 {
            get {
                return ResourceManager.GetString("ErrorText165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Struct array markers must be constant. 的本地化字符串。
        /// </summary>
        internal static string ErrorText166 {
            get {
                return ResourceManager.GetString("ErrorText166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enrichment array markers must be constant. 的本地化字符串。
        /// </summary>
        internal static string ErrorText167 {
            get {
                return ResourceManager.GetString("ErrorText167", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dimensions of array types must be constant expressions. 的本地化字符串。
        /// </summary>
        internal static string ErrorText168 {
            get {
                return ResourceManager.GetString("ErrorText168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   did not match any defined fields or properties. 的本地化字符串。
        /// </summary>
        internal static string ErrorText169 {
            get {
                return ResourceManager.GetString("ErrorText169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A delegate can not be called the same name as a primitive. 的本地化字符串。
        /// </summary>
        internal static string ErrorText17 {
            get {
                return ResourceManager.GetString("ErrorText17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   matched multiple defined fields or properties 的本地化字符串。
        /// </summary>
        internal static string ErrorText170 {
            get {
                return ResourceManager.GetString("ErrorText170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to use struct in classes, constructors and deconstructors. Use this instead. 的本地化字符串。
        /// </summary>
        internal static string ErrorText171 {
            get {
                return ResourceManager.GetString("ErrorText171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  did not match any defined struct fields. 的本地化字符串。
        /// </summary>
        internal static string ErrorText172 {
            get {
                return ResourceManager.GetString("ErrorText172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found multiple matching declarations 的本地化字符串。
        /// </summary>
        internal static string ErrorText173 {
            get {
                return ResourceManager.GetString("ErrorText173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  did not match any definitions. 的本地化字符串。
        /// </summary>
        internal static string ErrorText174 {
            get {
                return ResourceManager.GetString("ErrorText174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found no matching declarations 的本地化字符串。
        /// </summary>
        internal static string ErrorText175 {
            get {
                return ResourceManager.GetString("ErrorText175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whatever that is, it&apos;s not allowed in a type 的本地化字符串。
        /// </summary>
        internal static string ErrorText176 {
            get {
                return ResourceManager.GetString("ErrorText176", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid type name. Must be &quot;&lt;namespace&gt;.&lt;struct name&gt;&quot;. 的本地化字符串。
        /// </summary>
        internal static string ErrorText177 {
            get {
                return ResourceManager.GetString("ErrorText177", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The ? operator can only be used in statements. 的本地化字符串。
        /// </summary>
        internal static string ErrorText178 {
            get {
                return ResourceManager.GetString("ErrorText178", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enum member 的本地化字符串。
        /// </summary>
        internal static string ErrorText179 {
            get {
                return ResourceManager.GetString("ErrorText179", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only void return are allowed here. 的本地化字符串。
        /// </summary>
        internal static string ErrorText18 {
            get {
                return ResourceManager.GetString("ErrorText18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found multiple enum members with the value  的本地化字符串。
        /// </summary>
        internal static string ErrorText180 {
            get {
                return ResourceManager.GetString("ErrorText180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Typedefs can&apos;t be marked as protected. 的本地化字符串。
        /// </summary>
        internal static string ErrorText181 {
            get {
                return ResourceManager.GetString("ErrorText181", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom operators must have exactly two parameters. 的本地化字符串。
        /// </summary>
        internal static string ErrorText182 {
            get {
                return ResourceManager.GetString("ErrorText182", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Constant fields must have an initializer 的本地化字符串。
        /// </summary>
        internal static string ErrorText183 {
            get {
                return ResourceManager.GetString("ErrorText183", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only fields inside structs or classes can be marked as protected. 的本地化字符串。
        /// </summary>
        internal static string ErrorText184 {
            get {
                return ResourceManager.GetString("ErrorText184", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This type of property declaration must be in a struct, class or enrichment. 的本地化字符串。
        /// </summary>
        internal static string ErrorText185 {
            get {
                return ResourceManager.GetString("ErrorText185", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assignments have to be inside methods 的本地化字符串。
        /// </summary>
        internal static string ErrorText186 {
            get {
                return ResourceManager.GetString("ErrorText186", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The keyword value can only be used in property setters 的本地化字符串。
        /// </summary>
        internal static string ErrorText187 {
            get {
                return ResourceManager.GetString("ErrorText187", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Break statements must be inside for, while or switch statements 的本地化字符串。
        /// </summary>
        internal static string ErrorText188 {
            get {
                return ResourceManager.GetString("ErrorText188", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Continue statements must be inside for or while statemetns 的本地化字符串。
        /// </summary>
        internal static string ErrorText189 {
            get {
                return ResourceManager.GetString("ErrorText189", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 String obfuscation will not work in this context. I had some problems with triggers being initialized incorrectly. 的本地化字符串。
        /// </summary>
        internal static string ErrorText19 {
            get {
                return ResourceManager.GetString("ErrorText19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Const variables must have an initializer 的本地化字符串。
        /// </summary>
        internal static string ErrorText190 {
            get {
                return ResourceManager.GetString("ErrorText190", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameters can not be const 的本地化字符串。
        /// </summary>
        internal static string ErrorText191 {
            get {
                return ResourceManager.GetString("ErrorText191", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Triggers can not be marked as protected. 的本地化字符串。
        /// </summary>
        internal static string ErrorText192 {
            get {
                return ResourceManager.GetString("ErrorText192", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A deconstructor can&apos;t take parameters 的本地化字符串。
        /// </summary>
        internal static string ErrorText193 {
            get {
                return ResourceManager.GetString("ErrorText193", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A deconstructors in enrichments can&apos;t be protected. 的本地化字符串。
        /// </summary>
        internal static string ErrorText194 {
            get {
                return ResourceManager.GetString("ErrorText194", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delegates can not have a body. 的本地化字符串。
        /// </summary>
        internal static string ErrorText195 {
            get {
                return ResourceManager.GetString("ErrorText195", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delegates may not be marked as inline. 的本地化字符串。
        /// </summary>
        internal static string ErrorText196 {
            get {
                return ResourceManager.GetString("ErrorText196", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delegates may not be marked as trigger. 的本地化字符串。
        /// </summary>
        internal static string ErrorText197 {
            get {
                return ResourceManager.GetString("ErrorText197", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delegates may not be marked as static. 的本地化字符串。
        /// </summary>
        internal static string ErrorText198 {
            get {
                return ResourceManager.GetString("ErrorText198", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delegates may not be marked as native. 的本地化字符串。
        /// </summary>
        internal static string ErrorText199 {
            get {
                return ResourceManager.GetString("ErrorText199", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It is not possible to override fields. 的本地化字符串。
        /// </summary>
        internal static string ErrorText2 {
            get {
                return ResourceManager.GetString("ErrorText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other field string 的本地化字符串。
        /// </summary>
        internal static string ErrorText20 {
            get {
                return ResourceManager.GetString("ErrorText20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only methods inside structs or classes can be marked as protected. 的本地化字符串。
        /// </summary>
        internal static string ErrorText200 {
            get {
                return ResourceManager.GetString("ErrorText200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Structs or classes can not be marked as protected. 的本地化字符串。
        /// </summary>
        internal static string ErrorText201 {
            get {
                return ResourceManager.GetString("ErrorText201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can only cast to string, text, int or fixed. 的本地化字符串。
        /// </summary>
        internal static string ErrorText202 {
            get {
                return ResourceManager.GetString("ErrorText202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A local declaration must be inside a block 的本地化字符串。
        /// </summary>
        internal static string ErrorText203 {
            get {
                return ResourceManager.GetString("ErrorText203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected a variable name 的本地化字符串。
        /// </summary>
        internal static string ErrorText204 {
            get {
                return ResourceManager.GetString("ErrorText204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected an initializer 的本地化字符串。
        /// </summary>
        internal static string ErrorText205 {
            get {
                return ResourceManager.GetString("ErrorText205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected macro name 的本地化字符串。
        /// </summary>
        internal static string ErrorText206 {
            get {
                return ResourceManager.GetString("ErrorText206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can&apos;t declare new macros inside a macro. 的本地化字符串。
        /// </summary>
        internal static string ErrorText207 {
            get {
                return ResourceManager.GetString("ErrorText207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current macro 的本地化字符串。
        /// </summary>
        internal static string ErrorText208 {
            get {
                return ResourceManager.GetString("ErrorText208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found no matching #endmacro 的本地化字符串。
        /// </summary>
        internal static string ErrorText209 {
            get {
                return ResourceManager.GetString("ErrorText209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you dont use an explicit string literal here, it will not be possible to rename triggers 的本地化字符串。
        /// </summary>
        internal static string ErrorText21 {
            get {
                return ResourceManager.GetString("ErrorText21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected identifier or right parenthesis 的本地化字符串。
        /// </summary>
        internal static string ErrorText210 {
            get {
                return ResourceManager.GetString("ErrorText210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected comma or right parenthesis 的本地化字符串。
        /// </summary>
        internal static string ErrorText211 {
            get {
                return ResourceManager.GetString("ErrorText211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conflicting macro 的本地化字符串。
        /// </summary>
        internal static string ErrorText212 {
            get {
                return ResourceManager.GetString("ErrorText212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found multiple macros with same signature. 的本地化字符串。
        /// </summary>
        internal static string ErrorText213 {
            get {
                return ResourceManager.GetString("ErrorText213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Macro invocation not closed 的本地化字符串。
        /// </summary>
        internal static string ErrorText214 {
            get {
                return ResourceManager.GetString("ErrorText214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected right parenthesis 的本地化字符串。
        /// </summary>
        internal static string ErrorText215 {
            get {
                return ResourceManager.GetString("ErrorText215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Macro in cycle 的本地化字符串。
        /// </summary>
        internal static string ErrorText216 {
            get {
                return ResourceManager.GetString("ErrorText216", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found a cycle in macros 的本地化字符串。
        /// </summary>
        internal static string ErrorText217 {
            get {
                return ResourceManager.GetString("ErrorText217", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No matching macro found. 的本地化字符串。
        /// </summary>
        internal static string ErrorText218 {
            get {
                return ResourceManager.GetString("ErrorText218", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unused method 的本地化字符串。
        /// </summary>
        internal static string ErrorText219 {
            get {
                return ResourceManager.GetString("ErrorText219", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other non literal TriggerCreate call 的本地化字符串。
        /// </summary>
        internal static string ErrorText22 {
            get {
                return ResourceManager.GetString("ErrorText22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ] expecting: 的本地化字符串。
        /// </summary>
        internal static string ErrorText220 {
            get {
                return ResourceManager.GetString("ErrorText220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can only specify one library name. 的本地化字符串。
        /// </summary>
        internal static string ErrorText23 {
            get {
                return ResourceManager.GetString("ErrorText23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can only specify one library version. 的本地化字符串。
        /// </summary>
        internal static string ErrorText24 {
            get {
                return ResourceManager.GetString("ErrorText24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid library name. 的本地化字符串。
        /// </summary>
        internal static string ErrorText25 {
            get {
                return ResourceManager.GetString("ErrorText25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid library version. 的本地化字符串。
        /// </summary>
        internal static string ErrorText26 {
            get {
                return ResourceManager.GetString("ErrorText26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid format. It must be on the form &quot;(lib1:ver1),lib2:ver2,...&quot; 的本地化字符串。
        /// </summary>
        internal static string ErrorText27 {
            get {
                return ResourceManager.GetString("ErrorText27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The library  的本地化字符串。
        /// </summary>
        internal static string ErrorText28 {
            get {
                return ResourceManager.GetString("ErrorText28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  is marked as required, but could not be found. 的本地化字符串。
        /// </summary>
        internal static string ErrorText29 {
            get {
                return ResourceManager.GetString("ErrorText29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A struct can not inherit from a class. 的本地化字符串。
        /// </summary>
        internal static string ErrorText3 {
            get {
                return ResourceManager.GetString("ErrorText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Member of cycle 的本地化字符串。
        /// </summary>
        internal static string ErrorText30 {
            get {
                return ResourceManager.GetString("ErrorText30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cycle of libaray dependancies found. One of them will not have all it&apos;s dependancies initialized. 的本地化字符串。
        /// </summary>
        internal static string ErrorText31 {
            get {
                return ResourceManager.GetString("ErrorText31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other local variable 的本地化字符串。
        /// </summary>
        internal static string ErrorText32 {
            get {
                return ResourceManager.GetString("ErrorText32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can not have two local varaiables within same scope who has the same name 的本地化字符串。
        /// </summary>
        internal static string ErrorText33 {
            get {
                return ResourceManager.GetString("ErrorText33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A paramter can not be marked as both ref and out. 的本地化字符串。
        /// </summary>
        internal static string ErrorText34 {
            get {
                return ResourceManager.GetString("ErrorText34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The keyword global can only be used inside methods 的本地化字符串。
        /// </summary>
        internal static string ErrorText35 {
            get {
                return ResourceManager.GetString("ErrorText35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When the keyword struct is used in this context, it has to be inside a method. 的本地化字符串。
        /// </summary>
        internal static string ErrorText36 {
            get {
                return ResourceManager.GetString("ErrorText36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target trigger not found 的本地化字符串。
        /// </summary>
        internal static string ErrorText37 {
            get {
                return ResourceManager.GetString("ErrorText37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matching method 的本地化字符串。
        /// </summary>
        internal static string ErrorText38 {
            get {
                return ResourceManager.GetString("ErrorText38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple target triggers found 的本地化字符串。
        /// </summary>
        internal static string ErrorText39 {
            get {
                return ResourceManager.GetString("ErrorText39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overridden  的本地化字符串。
        /// </summary>
        internal static string ErrorText4 {
            get {
                return ResourceManager.GetString("ErrorText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TriggerCreate that does not have a constant literal 的本地化字符串。
        /// </summary>
        internal static string ErrorText40 {
            get {
                return ResourceManager.GetString("ErrorText40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trigger 的本地化字符串。
        /// </summary>
        internal static string ErrorText41 {
            get {
                return ResourceManager.GetString("ErrorText41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have a non constant TriggerCreate. This prevent the compiler from renaming triggers. You also have two triggers with the same name though. 的本地化字符串。
        /// </summary>
        internal static string ErrorText42 {
            get {
                return ResourceManager.GetString("ErrorText42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must specify the dimentions of the array here 的本地化字符串。
        /// </summary>
        internal static string ErrorText43 {
            get {
                return ResourceManager.GetString("ErrorText43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Base type must be a struct or a class. 的本地化字符串。
        /// </summary>
        internal static string ErrorText44 {
            get {
                return ResourceManager.GetString("ErrorText44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number of generic variables does not match. 的本地化字符串。
        /// </summary>
        internal static string ErrorText45 {
            get {
                return ResourceManager.GetString("ErrorText45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target  的本地化字符串。
        /// </summary>
        internal static string ErrorText46 {
            get {
                return ResourceManager.GetString("ErrorText46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target struct is a generic type. You must specify types for the generics. 的本地化字符串。
        /// </summary>
        internal static string ErrorText47 {
            get {
                return ResourceManager.GetString("ErrorText47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matching  的本地化字符串。
        /// </summary>
        internal static string ErrorText48 {
            get {
                return ResourceManager.GetString("ErrorText48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find any types matching  的本地化字符串。
        /// </summary>
        internal static string ErrorText49 {
            get {
                return ResourceManager.GetString("ErrorText49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enherited class 的本地化字符串。
        /// </summary>
        internal static string ErrorText5 {
            get {
                return ResourceManager.GetString("ErrorText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matches primitive 的本地化字符串。
        /// </summary>
        internal static string ErrorText50 {
            get {
                return ResourceManager.GetString("ErrorText50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matching typedef 的本地化字符串。
        /// </summary>
        internal static string ErrorText51 {
            get {
                return ResourceManager.GetString("ErrorText51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matching  的本地化字符串。
        /// </summary>
        internal static string ErrorText52 {
            get {
                return ResourceManager.GetString("ErrorText52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matching delegate 的本地化字符串。
        /// </summary>
        internal static string ErrorText53 {
            get {
                return ResourceManager.GetString("ErrorText53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matching generic 的本地化字符串。
        /// </summary>
        internal static string ErrorText54 {
            get {
                return ResourceManager.GetString("ErrorText54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found multiple types matching  的本地化字符串。
        /// </summary>
        internal static string ErrorText55 {
            get {
                return ResourceManager.GetString("ErrorText55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can not enrich this type. 的本地化字符串。
        /// </summary>
        internal static string ErrorText56 {
            get {
                return ResourceManager.GetString("ErrorText56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zero division during constant folding. 的本地化字符串。
        /// </summary>
        internal static string ErrorText57 {
            get {
                return ResourceManager.GetString("ErrorText57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Division by zero 的本地化字符串。
        /// </summary>
        internal static string ErrorText58 {
            get {
                return ResourceManager.GetString("ErrorText58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dimensions of array types must integer expressions. 的本地化字符串。
        /// </summary>
        internal static string ErrorText59 {
            get {
                return ResourceManager.GetString("ErrorText59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It is not possible to override methods. 的本地化字符串。
        /// </summary>
        internal static string ErrorText6 {
            get {
                return ResourceManager.GetString("ErrorText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matching field 的本地化字符串。
        /// </summary>
        internal static string ErrorText60 {
            get {
                return ResourceManager.GetString("ErrorText60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dimensions of array types must be constant expressions. 的本地化字符串。
        /// </summary>
        internal static string ErrorText61 {
            get {
                return ResourceManager.GetString("ErrorText61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matching property 的本地化字符串。
        /// </summary>
        internal static string ErrorText62 {
            get {
                return ResourceManager.GetString("ErrorText62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Candidate 的本地化字符串。
        /// </summary>
        internal static string ErrorText63 {
            get {
                return ResourceManager.GetString("ErrorText63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unused struct:  的本地化字符串。
        /// </summary>
        internal static string ErrorText64 {
            get {
                return ResourceManager.GetString("ErrorText64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unread field:  的本地化字符串。
        /// </summary>
        internal static string ErrorText65 {
            get {
                return ResourceManager.GetString("ErrorText65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have unused definitions. 的本地化字符串。
        /// </summary>
        internal static string ErrorText66 {
            get {
                return ResourceManager.GetString("ErrorText66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unread local:  的本地化字符串。
        /// </summary>
        internal static string ErrorText67 {
            get {
                return ResourceManager.GetString("ErrorText67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method in cycle 的本地化字符串。
        /// </summary>
        internal static string ErrorText68 {
            get {
                return ResourceManager.GetString("ErrorText68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are not allowed to make a cycle of method calls with methods marked with inline. 的本地化字符串。
        /// </summary>
        internal static string ErrorText69 {
            get {
                return ResourceManager.GetString("ErrorText69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It is not possible to override properties. 的本地化字符串。
        /// </summary>
        internal static string ErrorText7 {
            get {
                return ResourceManager.GetString("ErrorText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Struct in cycle 的本地化字符串。
        /// </summary>
        internal static string ErrorText70 {
            get {
                return ResourceManager.GetString("ErrorText70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are not allowed to make a cyclic dependancy with structs. 的本地化字符串。
        /// </summary>
        internal static string ErrorText71 {
            get {
                return ResourceManager.GetString("ErrorText71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found no matching properties or arrays 的本地化字符串。
        /// </summary>
        internal static string ErrorText72 {
            get {
                return ResourceManager.GetString("ErrorText72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found multiple matching array indexes. 的本地化字符串。
        /// </summary>
        internal static string ErrorText73 {
            get {
                return ResourceManager.GetString("ErrorText73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matches normal array index. 的本地化字符串。
        /// </summary>
        internal static string ErrorText74 {
            get {
                return ResourceManager.GetString("ErrorText74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property has no getter 的本地化字符串。
        /// </summary>
        internal static string ErrorText75 {
            get {
                return ResourceManager.GetString("ErrorText75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The left side of the . must be of type struct, class, or something which is enriched 的本地化字符串。
        /// </summary>
        internal static string ErrorText76 {
            get {
                return ResourceManager.GetString("ErrorText76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matching enrichment 的本地化字符串。
        /// </summary>
        internal static string ErrorText77 {
            get {
                return ResourceManager.GetString("ErrorText77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No matching property found in enrichment. 的本地化字符串。
        /// </summary>
        internal static string ErrorText78 {
            get {
                return ResourceManager.GetString("ErrorText78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to find a field in the struct called  的本地化字符串。
        /// </summary>
        internal static string ErrorText79 {
            get {
                return ResourceManager.GetString("ErrorText79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can not make a cycle of inheritance. 的本地化字符串。
        /// </summary>
        internal static string ErrorText8 {
            get {
                return ResourceManager.GetString("ErrorText8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matching struct: 的本地化字符串。
        /// </summary>
        internal static string ErrorText80 {
            get {
                return ResourceManager.GetString("ErrorText80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The struct variable is marked as private. It can only be accessed from inside the struct where it is defined. 的本地化字符串。
        /// </summary>
        internal static string ErrorText81 {
            get {
                return ResourceManager.GetString("ErrorText81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matching local 的本地化字符串。
        /// </summary>
        internal static string ErrorText82 {
            get {
                return ResourceManager.GetString("ErrorText82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The struct variable is marked as protected. It can only be accessed from inside the struct where it is defined, or a subtype thereof. 的本地化字符串。
        /// </summary>
        internal static string ErrorText83 {
            get {
                return ResourceManager.GetString("ErrorText83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variable is marked as static. Access it with  的本地化字符串。
        /// </summary>
        internal static string ErrorText84 {
            get {
                return ResourceManager.GetString("ErrorText84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matching struct field 的本地化字符串。
        /// </summary>
        internal static string ErrorText85 {
            get {
                return ResourceManager.GetString("ErrorText85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variable is not marked as static. Access it with you must access it through an instance of  的本地化字符串。
        /// </summary>
        internal static string ErrorText86 {
            get {
                return ResourceManager.GetString("ErrorText86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The struct property is marked as private. It can only be accessed from inside the struct where it is defined. 的本地化字符串。
        /// </summary>
        internal static string ErrorText87 {
            get {
                return ResourceManager.GetString("ErrorText87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The struct property is marked as protected. It can only be accessed from inside the struct where it is defined, or a subtype thereof. 的本地化字符串。
        /// </summary>
        internal static string ErrorText88 {
            get {
                return ResourceManager.GetString("ErrorText88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property is marked as static. Access it with 的本地化字符串。
        /// </summary>
        internal static string ErrorText89 {
            get {
                return ResourceManager.GetString("ErrorText89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No type found named  的本地化字符串。
        /// </summary>
        internal static string ErrorText9 {
            get {
                return ResourceManager.GetString("ErrorText9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Matching struct property 的本地化字符串。
        /// </summary>
        internal static string ErrorText90 {
            get {
                return ResourceManager.GetString("ErrorText90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property is not marked as static. Access it with you must access it through an instance of  的本地化字符串。
        /// </summary>
        internal static string ErrorText91 {
            get {
                return ResourceManager.GetString("ErrorText91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to use struct fields outside of methods. 的本地化字符串。
        /// </summary>
        internal static string ErrorText92 {
            get {
                return ResourceManager.GetString("ErrorText92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type in a delegate creation expression must be a delegate type 的本地化字符串。
        /// </summary>
        internal static string ErrorText93 {
            get {
                return ResourceManager.GetString("ErrorText93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method must match exactly. Implicitly matching methods are not allowed. 的本地化字符串。
        /// </summary>
        internal static string ErrorText94 {
            get {
                return ResourceManager.GetString("ErrorText94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method must be referenced from a dynamic context. 的本地化字符串。
        /// </summary>
        internal static string ErrorText95 {
            get {
                return ResourceManager.GetString("ErrorText95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Method must be a global method, or static struct/class method, or it must be refferenced from a dynamic context. 的本地化字符串。
        /// </summary>
        internal static string ErrorText96 {
            get {
                return ResourceManager.GetString("ErrorText96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter 的本地化字符串。
        /// </summary>
        internal static string ErrorText97 {
            get {
                return ResourceManager.GetString("ErrorText97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  marked as out is used before a value has been assigned to it. 的本地化字符串。
        /// </summary>
        internal static string ErrorText98 {
            get {
                return ResourceManager.GetString("ErrorText98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can not access a non-static variable in a static context. 的本地化字符串。
        /// </summary>
        internal static string ErrorText99 {
            get {
                return ResourceManager.GetString("ErrorText99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transforming code ( 的本地化字符串。
        /// </summary>
        internal static string FT_Text1 {
            get {
                return ResourceManager.GetString("FT_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Transforming properties to methods (Phase 1). 的本地化字符串。
        /// </summary>
        internal static string FT_Text10 {
            get {
                return ResourceManager.GetString("FT_Text10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Removing dead code. 的本地化字符串。
        /// </summary>
        internal static string FT_Text11 {
            get {
                return ResourceManager.GetString("FT_Text11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Moving methods members out of structs. 的本地化字符串。
        /// </summary>
        internal static string FT_Text12 {
            get {
                return ResourceManager.GetString("FT_Text12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Invoking initializers. 的本地化字符串。
        /// </summary>
        internal static string FT_Text13 {
            get {
                return ResourceManager.GetString("FT_Text13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Moving assignments out to their own statement. 的本地化字符串。
        /// </summary>
        internal static string FT_Text14 {
            get {
                return ResourceManager.GetString("FT_Text14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Transforming properties to methods (Phase 2). 的本地化字符串。
        /// </summary>
        internal static string FT_Text15 {
            get {
                return ResourceManager.GetString("FT_Text15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Fixing invokes (sync/assync). 的本地化字符串。
        /// </summary>
        internal static string FT_Text16 {
            get {
                return ResourceManager.GetString("FT_Text16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Removing empty structs. 的本地化字符串。
        /// </summary>
        internal static string FT_Text17 {
            get {
                return ResourceManager.GetString("FT_Text17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Making delegates. 的本地化字符串。
        /// </summary>
        internal static string FT_Text18 {
            get {
                return ResourceManager.GetString("FT_Text18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Transforming inline methods (Run 1). 的本地化字符串。
        /// </summary>
        internal static string FT_Text19 {
            get {
                return ResourceManager.GetString("FT_Text19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Removing namespaces. 的本地化字符串。
        /// </summary>
        internal static string FT_Text2 {
            get {
                return ResourceManager.GetString("FT_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Removing unneeded ref parameters. 的本地化字符串。
        /// </summary>
        internal static string FT_Text20 {
            get {
                return ResourceManager.GetString("FT_Text20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Expanding struct equality tests. 的本地化字符串。
        /// </summary>
        internal static string FT_Text21 {
            get {
                return ResourceManager.GetString("FT_Text21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Transforming pointers. 的本地化字符串。
        /// </summary>
        internal static string FT_Text22 {
            get {
                return ResourceManager.GetString("FT_Text22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Transforming inline methods (Run 2). 的本地化字符串。
        /// </summary>
        internal static string FT_Text23 {
            get {
                return ResourceManager.GetString("FT_Text23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Splitting local structs into primitives. 的本地化字符串。
        /// </summary>
        internal static string FT_Text24 {
            get {
                return ResourceManager.GetString("FT_Text24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Removnig redundant assignments. 的本地化字符串。
        /// </summary>
        internal static string FT_Text25 {
            get {
                return ResourceManager.GetString("FT_Text25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Folding constants. 的本地化字符串。
        /// </summary>
        internal static string FT_Text26 {
            get {
                return ResourceManager.GetString("FT_Text26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Optimizing. 的本地化字符串。
        /// </summary>
        internal static string FT_Text27 {
            get {
                return ResourceManager.GetString("FT_Text27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Making short names. 的本地化字符串。
        /// </summary>
        internal static string FT_Text28 {
            get {
                return ResourceManager.GetString("FT_Text28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Making unique names. 的本地化字符串。
        /// </summary>
        internal static string FT_Text29 {
            get {
                return ResourceManager.GetString("FT_Text29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Moving static members out. 的本地化字符串。
        /// </summary>
        internal static string FT_Text3 {
            get {
                return ResourceManager.GetString("FT_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Renaming references to variables whose names have changed. 的本地化字符串。
        /// </summary>
        internal static string FT_Text30 {
            get {
                return ResourceManager.GetString("FT_Text30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Obfuscating strings. 的本地化字符串。
        /// </summary>
        internal static string FT_Text31 {
            get {
                return ResourceManager.GetString("FT_Text31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Mergeing methods if they are the same, 的本地化字符串。
        /// </summary>
        internal static string FT_Text32 {
            get {
                return ResourceManager.GetString("FT_Text32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Generating includes (merging to one file if selected). 的本地化字符串。
        /// </summary>
        internal static string FT_Text33 {
            get {
                return ResourceManager.GetString("FT_Text33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Removing constant variables. 的本地化字符串。
        /// </summary>
        internal static string FT_Text4 {
            get {
                return ResourceManager.GetString("FT_Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Locating main entry. 的本地化字符串。
        /// </summary>
        internal static string FT_Text5 {
            get {
                return ResourceManager.GetString("FT_Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The source file containing the main entry function should be placed in root folder to be able to overwrite MapScript.galaxy. 的本地化字符串。
        /// </summary>
        internal static string FT_Text6 {
            get {
                return ResourceManager.GetString("FT_Text6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Setting default values for struct variables. 的本地化字符串。
        /// </summary>
        internal static string FT_Text7 {
            get {
                return ResourceManager.GetString("FT_Text7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Transforming expression ifs. 的本地化字符串。
        /// </summary>
        internal static string FT_Text8 {
            get {
                return ResourceManager.GetString("FT_Text8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ): Renaming unicode identifiers and strings. 的本地化字符串。
        /// </summary>
        internal static string FT_Text9 {
            get {
                return ResourceManager.GetString("FT_Text9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The compiler is already working. Close this message box and try again.
        ///If this takes more than a couple of seconds, it&apos;s most likely an infinite loop. 的本地化字符串。
        /// </summary>
        internal static string GC_Text1 {
            get {
                return ResourceManager.GetString("GC_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Linking usages to declarations 的本地化字符串。
        /// </summary>
        internal static string GC_Text10 {
            get {
                return ResourceManager.GetString("GC_Text10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking types 的本地化字符串。
        /// </summary>
        internal static string GC_Text11 {
            get {
                return ResourceManager.GetString("GC_Text11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transforming code 的本地化字符串。
        /// </summary>
        internal static string GC_Text12 {
            get {
                return ResourceManager.GetString("GC_Text12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generating code 的本地化字符串。
        /// </summary>
        internal static string GC_Text13 {
            get {
                return ResourceManager.GetString("GC_Text13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compilation finished successfully 的本地化字符串。
        /// </summary>
        internal static string GC_Text14 {
            get {
                return ResourceManager.GetString("GC_Text14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compilation terminated with errors 的本地化字符串。
        /// </summary>
        internal static string GC_Text15 {
            get {
                return ResourceManager.GetString("GC_Text15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compiler already running 的本地化字符串。
        /// </summary>
        internal static string GC_Text2 {
            get {
                return ResourceManager.GetString("GC_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parsing 的本地化字符串。
        /// </summary>
        internal static string GC_Text3 {
            get {
                return ResourceManager.GetString("GC_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weeding 的本地化字符串。
        /// </summary>
        internal static string GC_Text4 {
            get {
                return ResourceManager.GetString("GC_Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Building enviroment 的本地化字符串。
        /// </summary>
        internal static string GC_Text5 {
            get {
                return ResourceManager.GetString("GC_Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking enviroment 的本地化字符串。
        /// </summary>
        internal static string GC_Text6 {
            get {
                return ResourceManager.GetString("GC_Text6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Linking types 的本地化字符串。
        /// </summary>
        internal static string GC_Text7 {
            get {
                return ResourceManager.GetString("GC_Text7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fixing generics 的本地化字符串。
        /// </summary>
        internal static string GC_Text8 {
            get {
                return ResourceManager.GetString("GC_Text8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fixing enheritance 的本地化字符串。
        /// </summary>
        internal static string GC_Text9 {
            get {
                return ResourceManager.GetString("GC_Text9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to open the map. 的本地化字符串。
        /// </summary>
        internal static string ME_Text1 {
            get {
                return ResourceManager.GetString("ME_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file  的本地化字符串。
        /// </summary>
        internal static string ME_Text10 {
            get {
                return ResourceManager.GetString("ME_Text10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  already exists in the project folder. Do you wan&apos;t to overwrite it with the one from the map? 的本地化字符串。
        /// </summary>
        internal static string ME_Text11 {
            get {
                return ResourceManager.GetString("ME_Text11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Override 的本地化字符串。
        /// </summary>
        internal static string ME_Text12 {
            get {
                return ResourceManager.GetString("ME_Text12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occured while extracting  的本地化字符串。
        /// </summary>
        internal static string ME_Text13 {
            get {
                return ResourceManager.GetString("ME_Text13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  from the map. 的本地化字符串。
        /// </summary>
        internal static string ME_Text14 {
            get {
                return ResourceManager.GetString("ME_Text14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to read the file in an mpq. 的本地化字符串。
        /// </summary>
        internal static string ME_Text15 {
            get {
                return ResourceManager.GetString("ME_Text15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to open the map to fetch  的本地化字符串。
        /// </summary>
        internal static string ME_Text16 {
            get {
                return ResourceManager.GetString("ME_Text16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 . 的本地化字符串。
        /// </summary>
        internal static string ME_Text17 {
            get {
                return ResourceManager.GetString("ME_Text17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to open the file  的本地化字符串。
        /// </summary>
        internal static string ME_Text18 {
            get {
                return ResourceManager.GetString("ME_Text18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  in the mpq  的本地化字符串。
        /// </summary>
        internal static string ME_Text19 {
            get {
                return ResourceManager.GetString("ME_Text19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot name a file other than the root file as MapScript.galaxy 的本地化字符串。
        /// </summary>
        internal static string ME_Text2 {
            get {
                return ResourceManager.GetString("ME_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 . 的本地化字符串。
        /// </summary>
        internal static string ME_Text20 {
            get {
                return ResourceManager.GetString("ME_Text20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to copy  的本地化字符串。
        /// </summary>
        internal static string ME_Text3 {
            get {
                return ResourceManager.GetString("ME_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 to the map.
        ///There are most likely too many files.
        ///Try setting the &quot;Join output to one file&quot; flag in the options menu. 的本地化字符串。
        /// </summary>
        internal static string ME_Text4 {
            get {
                return ResourceManager.GetString("ME_Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to copy map. Is any files in the target directory in use? 的本地化字符串。
        /// </summary>
        internal static string ME_Text5 {
            get {
                return ResourceManager.GetString("ME_Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to open the source map for copying. 的本地化字符串。
        /// </summary>
        internal static string ME_Text6 {
            get {
                return ResourceManager.GetString("ME_Text6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to save the galaxy++ files to the map. Is it open in another program? 的本地化字符串。
        /// </summary>
        internal static string ME_Text7 {
            get {
                return ResourceManager.GetString("ME_Text7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to extract  的本地化字符串。
        /// </summary>
        internal static string ME_Text8 {
            get {
                return ResourceManager.GetString("ME_Text8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  from the map. 的本地化字符串。
        /// </summary>
        internal static string ME_Text9 {
            get {
                return ResourceManager.GetString("ME_Text9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing data 的本地化字符串。
        /// </summary>
        internal static string SCEF_MissData {
            get {
                return ResourceManager.GetString("SCEF_MissData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StarCraft 2 Executable not found. Note that you cannot use any of the StarCraft 2 natives before you specify the location. 的本地化字符串。
        /// </summary>
        internal static string SCEF_MissData_NotLoad_Text {
            get {
                return ResourceManager.GetString("SCEF_MissData_NotLoad_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I lost track of where StarCraft II is located. Can you help me? 的本地化字符串。
        /// </summary>
        internal static string SCEF_MissData_Text {
            get {
                return ResourceManager.GetString("SCEF_MissData_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I lost track of where Starcraft II is located. Can you help me? 的本地化字符串。
        /// </summary>
        internal static string TL_Text1 {
            get {
                return ResourceManager.GetString("TL_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing data 的本地化字符串。
        /// </summary>
        internal static string TL_Text2 {
            get {
                return ResourceManager.GetString("TL_Text2", resourceCulture);
            }
        }
    }
}
